image: python:3.6.3-jessie

pages:
  only:
    - master
  script:
    - pip install -r requirements.txt
    - pip install .
    - cd docs; make html
    - mv docs/.build/html public
  artifacts:
    paths:
      - public
