image: python:3.6.3-jessie

variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/pip-cache"

cache:
  paths:
    - "$CI_PROJECT_DIR/pip-cache"
  key: "$CI_PROJECT_ID"

before_script:
    - apt-get update --fix-missing && apt-get install -y pandoc
    - pip install -U pip
    - pip install opencv-python-headless pillow
    - pip install torch==1.6.0+cpu torchvision==0.7.0+cpu -f https://download.pytorch.org/whl/torch_stable.html
    - pip install -r develop.txt

stages:
  - test
  - deploy

lint:
  stage: test
  script:
    - make lint

unittest:
  stage: test
  only:
    - tags
    - master
    - develop
  script:
    - make unittest

doctest:
  stage: test
  only:
    - tags
    - master
    - develop
  script:
    - make doctest

pypi:
  stage: deploy
  only:
    refs:
      - tags
    variables:
      - $CI_SHOULD_DEPLOY == "1"
  script:
    - pip install -U twine wheel setuptools
    - python setup.py sdist bdist_wheel
    - twine check dist/*
    - twine upload --skip-existing dist/*

pypitest:
  stage: deploy
  only:
    refs:
      - master
    variables:
      - $CI_SHOULD_DEPLOY == "1"
  script:
    - pip install -U twine wheel setuptools
    - python setup.py sdist bdist_wheel
    - twine check dist/*
    - twine upload --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*

pages:
  stage: deploy
  only:
    refs:
      - tags
    variables:
      - $CI_SHOULD_DEPLOY == "1"
  script:
    - pip install IPython
    - cd docs; make html; cd ..
    - mv docs/.build/html public/
  artifacts:
    paths:
      - public
